#!/bin/bash


auth() {
    read -p "What is your Account Number: " ddi
    read -p "Whats your username:" username
    read -p "Whats your APIkey:" APIkey
    read -p "Which Datacenter? " dc
}

token() {
    token=`curl -s https://identity.api.rackspacecloud.com/v2.0/tokens -X POST \
    -d '{"auth":{"RAX-KSKEY:apiKeyCredentials":{"username":"'$username'", "apiKey":"'$APIkey'"}}}' \
    -H "Content-Type: application/json" | python -m json.tool  | sed -n '/expires/{n;p;}' |sed -e 's/^.*"id": "\(.*\)",/\1/'`
    echo "Your API Token is ---->  $token"
}

getservers() {
    curl -s -H "X-Auth-Token: $token" "https://$dc.servers.api.rackspacecloud.com/v2/$ddi/servers/detail" | python -m json.tool
}

rescue() {
    read -p "Which server would you like to rescue: " server
    curl -s -H "X-Auth-Token: $token" "https://$dc.servers.api.rackspacecloud.com/v2/$ddi/images" \
    | python -m json.tool |egrep '"id"|"name"'
    read -p "What image would you like:" image
    curl -s -X POST -H "X-Auth-Token: $token" -H "Content-type: application/json" \
    https://$dc.servers.api.rackspacecloud.com/v2/$ddi/servers/$server/action \
    -d '{"rescue": {"rescue_image_ref": "'$image'"}}' \
    | python -m json.tool
}

auth
token
getservers
rescue

