#!/bin/bash

######################################################## 
#Bash script to find the Interal IP for Load Balancers #
########################################################
 
echo "=================================================="
echo "         ServiceNet IP for Load Balancers         "
echo "=================================================="

read -p "Input Account #: " DDI 
read -p "Input Username: " USER
read -p "Input API Key: " API
read -p"Input Region (dfw ord lon iad hkg syd): " REGION
read -p "Input ID of Load Balancer: " LB

 
token=`curl -s https://identity.api.rackspacecloud.com/v2.0/tokens -X POST \
    -d '{"auth":{"RAX-KSKEY:apiKeyCredentials":{"username":"'$USER'", "apiKey":"'$API'"}}}' \
    -H "Content-Type: application/json" | python -m json.tool  | sed -n '/expires/{n;p;}' |sed -e 's/^.*"id": "\(.*\)",/\1/'`

echo -n -e "ServiceNet IP = "

curl -s -H "X-Auth-Token: $token" "https://$REGION.loadbalancers.api.rackspacecloud.com/v1.0/$DDI/loadbalancers/$LB" | python -mjson.tool | grep "ipv4Servicenet" | gawk '{ print $2 }' | sed 's/"//g' | sed 's/,//g'
 

