#!/bin/bash

auth() {
    read -p "What is your Account Number: " ddi
    read -p "Whats your username:" username
    read -p "Whats your APIkey:" APIkey
    read -p "Which Datacenter is the server in? " dc
}

token() {
    token=`curl -s https://identity.api.rackspacecloud.com/v2.0/tokens -X POST \
    -d '{"auth":{"RAX-KSKEY:apiKeyCredentials":{"username":"'$username'", "apiKey":"'$APIkey'"}}}' \
    -H "Content-Type: application/json" | python -m json.tool  | sed -n '/expires/{n;p;}' |sed -e 's/^.*"id": "\(.*\)",/\1/'`
    echo "Your API Token is ---->  $token"
}

listservers() {
    curl -s -H "X-Auth-Token: $token" "https://$dc.servers.api.rackspacecloud.com/v2/$ddi/servers" | python -m json.tool
}

password() {
    read -p "Which server do you want to change the password on? " id
    echo "Please use complex, random passwords with a minimum of 2 uppercase characters, 2 lowercase characters, 2 number, and 2 symbols with a minimum of 10 characters total"
    read -p "What would you like to change the root password to? " pass
    curl -s -X POST "https://$dc.servers.api.rackspacecloud.com/v2/$ddi/servers/$id/action" \
    -H "X-Auth-Token: $token" -H "Content-Type: application/json"  -d '{"changePassword" : {"adminPass" : "'$pass'"}}'
}

auth
token
listservers
password
